### ISSUE TITLE
Failed to install dependencies ("no solution found")

### ISSUE THREAD

**Issue by jeehoonkang** [rems-project/rmem#13]
I failed to install dependencies with the following error log:

```
$ opam --version 
2.0.5

$ ocamlc --version
4.10.0

$ opam install . 
[rmem.0.1] no changes from git+file:///kaist-cp-home/jeehoon.kang/Works/rmem#master
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
```

I wonder if this error is familiar to the developers.  Thanks!

**Comment by cp526** [comment]
The reason for this is probably that for some dependencies you currently still need to add the REMS opam repository. Sorry about that, the README did not say, I updated it now. For adding the REMS opam repository, run `opam repository add rems https://github.com/rems-project/opam-repository.git`.

**Comment by jeehoonkang** [comment]
Thank you!  But I still experience the same error:

```
$ opam repository 
[NOTE] These are the repositories in use by the current switch. Use '--all' to see all configured
       repositories.

<><> Repository configuration for switch 4.10.0 <><><><><><><><><><><><><><><><>
 1 rems    git+https://github.com/rems-project/opam-repository.git
 2 default https://opam.ocaml.org

$ opam install . 
[rmem.0.1] no changes from git+file:///kaist-cp-home/jeehoon.kang/Works/rmem#master
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
```

I believe it's because the opam repo (https://github.com/rems-project/opam-repository) supports only opam 1.2, not opam 2.0 (which I use).  I guess maybe it's also worth documenting in README?

**Comment by cp526** [comment]
Hi Jeehoon,

Sorry about that. Indeed the reason seems to be that the repository is an opam 1.2 repository.
We have an opam 2 branch on that repository and we're just looking into whether installation works when using that.

Best,
Christopher

**Comment by cp526** [comment]
I committed small changes to rmem and sail to hopefully get back to a working state. As for the opam repository, you can add the opam 2 repository via `opam repository add rems https://github.com/rems-project/opam-repository.git#opam2` .  This should have the dependencies needed for installing rmem.

**Comment by zlindaz2411** [comment]
Hi, I also have the same problem. I followed the instructions and I added the repository to opam repository, but when I do opam install rmem, it says: no packaged named rmem found. 
<img width="561" alt="Screenshot 2020-10-24 at 20 20 59" src="https://user-images.githubusercontent.com/32620429/97091798-6eecf480-1636-11eb-9bd8-9c0b43598621.png">

**Comment by cp526** [comment]
We seem to have had an error in our instructions for the rems opam repository. I just updated the README.
If you try remove the rems opam repository and then follow the updated instructions, does that work?

**Comment by zlindaz2411** [comment]
Still doesn't work even if I set the rems to be default
<img width="564" alt="Screenshot 2020-10-26 at 10 38 14" src="https://user-images.githubusercontent.com/32620429/97162626-5c2e0900-1777-11eb-862a-a5f4da3af789.png">

**Comment by cp526** [comment]
I just pushed the rmem package to the REMS repository. It seems to have been missing, sorry.
If you do `opam update` and try again, does that work?

**Comment by zlindaz2411** [comment]
Now it allows me to install, but I'm stuck in installing sail-riscv 0.5. And I think I need to install this, and then the rmem will get installed because now when I type in rmem, it says no command found.
<img width="577" alt="Screenshot 2020-10-26 at 12 01 37" src="https://user-images.githubusercontent.com/32620429/97170084-01021380-1783-11eb-9c78-a6bb584862e1.png">

**Comment by cp526** [comment]
I’ll forward this to the sail-riscv people.

In the mean time, if you don’t need RISC-V, one thing to try could be following the README steps for "Building and running rmem with command-line interface, with make” and in the last step instead of "make MODE=opt”  do  ""make MODE=opt ISA=AArch64,X86” (or whichever non-RISCV ISAs you’re interested in).

**Comment by bauereiss** [comment]
"z3: command not found" suggests that you might be missing some external dependencies of Sail that the opam package doesn't automatically install.  There are commands to install those for Ubuntu and Mac [here](https://github.com/rems-project/sail/blob/sail2/INSTALL.md), maybe that helps?

**Comment by zlindaz2411** [comment]
Thank you! It's installed.

**Comment by bauereiss** [comment]
I see the rmem README also gives a command to install external dependencies, but that is missing z3.  Maybe it should be added there?  There's also a z3 package in opam, by the way, but that only installs a z3 library, not a z3 executable, so that won't be enough for Sail.
